version: "3.6"

volumes:
  backend_logs:
  pgdata:
  postfix_spool:

services:
  backend:
    restart: always
    build: backend
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod,mail
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: oap:11800
      TZ: Europe/Brussels
      DB_USERNAME: ""
      DB_PASSWORD: ""
      DB_URL: ""
      AUTH_DB_USERNAME: ""
      AUTH_DB_PASSWORD: ""
      AUTH_DB_URL: ""
      LDAP_URL: ""
      LDAP_BASE: ""
      LDAP_USER_DN: ""
      LDAP_PASSWORD: ""
      AUTH_SERVICE_KEY: ""
    depends_on:
      - db
    volumes:
      - backend_logs:/app/logs:rw
    networks:
      - blokatgent
    logging:
      options:
        max-size: "100m"
        max-file: "5"

  db:
    image: postgres:12-alpine
    command: postgres -c 'max_connections=500' -c 'shared_buffers=1024' -c 'log_min_messages=notice'
    restart: always
    environment:
      POSTGRES_DB: blokatugent
      POSTGRES_USER: blokat
      POSTGRES_PASSWORD: "***REMOVED***"
      TZ: Europe/Brussels
      PGTZ: Europe/Brussels
    volumes:
      - pgdata:/var/lib/postgresql/data
    #  - ./backend/postgres.conf:/var/lib/postgresql/data/postgresql.conf

    networks:
      - blokatgent
    logging:
      options:
        max-size: "100m"
        max-file: "5"

  frontend:
    restart: always
    build: frontend
    ports:
      - "8091:80"
    networks:
      - blokatgent
    logging:
      options:
        max-size: "100m"
        max-file: "5"
  mailrelay:
    restart: always
    image: juanluisbaptiste/postfix:latest
    networks:
      - blokatgent
    expose:
      - "25"
    environment:
      SMTP_SERVER: "smtp.ugent.be"
      SMTP_PORT: "25"
      SERVER_HOSTNAME: "fireball.ugent.be"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - postfix_spool:/var/spool/postfix

networks:
  blokatgent:
    name: blokatgent
