DROP TABLE IF EXISTS translations;

CREATE TABLE translatables
(
    id         bigint generated by default as identity,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp,

    PRIMARY KEY (id)
);

CREATE TABLE translations
(
    id              bigint generated by default as identity,
    translatable_id bigint,
    language        varchar(2),
    value           text,
    created_at      timestamp default current_timestamp,
    updated_at      timestamp default current_timestamp,

    PRIMARY KEY (id, language),
    FOREIGN KEY (translatable_id) REFERENCES translatables (id)
);