volumes:
   pgdata-users:
networks:
  blokatgent:
    external:
      name: blokatgent


services:
  authentication:
    build: .
    ports:
      - "8087:8087"
    environment:
      NODE_ENV: staging
      POSTGRES_USER: blokat
      POSTGRES_PASSWORD: ""
      JWT_KEY: ""
      DATABASE_URL: "postgresql://blokat:***REMOVED***@user-db:5432/studieplekken_users?schema=public"
      BACKEND_SERVICE_KEY: ""
    networks:
      - blokatgent
    depends_on:
      - user-db

  user-db:
    image: postgres:12-alpine
    command: postgres -c 'max_connections=500' -c 'shared_buffers=1024' -c 'log_min_messages=notice'
    restart: always
    environment:
      POSTGRES_DB: studieplekken_users
      POSTGRES_USER: blokat
      POSTGRES_PASSWORD: "***REMOVED***"
      TZ: Europe/Brussels
      PGTZ: Europe/Brussels
    volumes:
      - pgdata-users:/var/lib/postgresql/data 
    networks:
      - blokatgent
