version: '3.6'

volumes:
  oap_database:

networks:
  blokatgent:
    external: true


services:
  oap:
    build: .
    restart: on-failure
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      TZ: Europe/Brussels
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://oap-db:3306/swtest
      SW_DATA_SOURCE_USER: sw
      SW_DATA_SOURCE_PASSWORD: "***REMOVED***"
    volumes:
      - ./oadb-libs:/oap-libs
#   volumes:
#     - oap_database:/var/lib/mysql
    networks:
      - blokatgent
    logging:
      options:
        max-size: "100m"
        max-file: "5"
  ui:
    image: apache/skywalking-ui:8.7.0
    depends_on:
      - oap
    links:
      - oap
    restart: on-failure
    ports:
      - 8000:8080
    environment:
      - TZ=Europe/Brussels
      - collector.ribbon.listOfServers=oap:12800
    networks:
      - blokatgent
  oap-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "***REMOVED***"
      MYSQL_DATABASE: swtest
      MYSQL_USER: sw
      MYSQL_PASSWORD: "***REMOVED***"
    networks:
      - blokatgent
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

#  prom:
#    image: prom/prometheus
