# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-auth:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    container:
      image: node:16-stretch
      env:
        POSTGRES_DB: db
        
    services:
      db:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: studieplekken_users_test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create meta-idp.xml from B64_SECRET1
        run: |
          mkdir -p authentication-service/blokat-authentication/config/auth/saml
          echo "$SECRET_DATA1" | base64 -i - -d > authentication-service/blokat-authentication/config/auth/saml/meta-idp.xml
        env:
          SECRET_DATA1: ${{ secrets.B64_META_IDP }}

      - name: Run tests
        run: |
          apt-get update -y && apt-get install netcat -y
          bash ./scripts/wait_for_service db 5432
          cd authentication-service/blokat-authentication
          yarn install
          DATABASE_URL="postgresql://postgres:postgres@db:5432/studieplekken_users_test?schema=public" npx prisma migrate deploy
          yarn run test

      - name: Delete secret file
        run: |
          rm authentication-service/blokat-authentication/config/auth/saml/meta-idp.xml
        if: always()
